apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: TestNamesRestApi
spec:
  selector:
    matchLabels:
      app: TestNamesRestApi
  replicas: 1 # tells deployment to run 3 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: TestNamesRestApi
    spec:
      containers:
      - name: TestNamesRestApi
        image: gcr.io/<project-id>/<image-name>:versionImagen
        ports:
        - containerPort: 8099
          name: server
        - containerPort: 8099
          name: management
        readinessProbe:
          httpGet:
            path: /health
            port: 8099
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: TestNamesRestApi
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"8099":"backend-config"}}'
spec:
  ports:
  - port: 8099
    targetPort: 8099
    name: http
  selector:
    app: TestNamesRestApi
  type: NodePort